_markerRef = createMarker ["BIS_mrk_frontline_AAF_1", [14834.6,16413.2,0]];
_markerRef setMarkerColor "ColorGUER";
_markerRef setMarkerSize [1500,1000];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -223.701;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_mrk_frontline_AAF_2", [11610.6,11740.5,0]];
_markerRef setMarkerColor "ColorGUER";
_markerRef setMarkerSize [500,700];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -140.86;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_mrk_frontline_AAF_3", [16814.8,12575.8,0]];
_markerRef setMarkerColor "ColorGUER";
_markerRef setMarkerSize [900,800];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -223.701;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_mrk_frontline_AAF_4", [23107.8,18661.4,0]];
_markerRef setMarkerColor "ColorGUER";
_markerRef setMarkerSize [600,400];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -273.304;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";

_markerRef = createMarker ["BIS_ORBAT_AAF_1", [11257,12441.6,0]];
_markerRef setMarkerColor "ColorGUER";
_markerRef setMarkerSize [1.5,1.5];
_markerRef setMarkerType "n_air";
_markerRef setMarkerDir -1;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_AAF_2", [14241,16952.9,0]];
_markerRef setMarkerColor "ColorGUER";
_markerRef setMarkerSize [1.5,1.5];
_markerRef setMarkerType "n_plane";
_markerRef setMarkerDir -1;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_AAF_3", [11961.8,11287.5,0]];
_markerRef setMarkerColor "ColorGUER";
_markerRef setMarkerSize [1.5,1.5];
_markerRef setMarkerType "n_inf";
_markerRef setMarkerDir 1;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_AAF_4", [17128.7,13026.5,0]];
_markerRef setMarkerColor "ColorGUER";
_markerRef setMarkerSize [1.5,1.5];
_markerRef setMarkerType "n_hq";
_markerRef setMarkerDir 0.5;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_AAF_5", [15226.9,15967.9,0]];
_markerRef setMarkerColor "ColorGUER";
_markerRef setMarkerSize [1.5,1.5];
_markerRef setMarkerType "n_mech_inf";
_markerRef setMarkerDir 1;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_AAF_6", [14166.1,15379.2,0]];
_markerRef setMarkerColor "ColorGUER";
_markerRef setMarkerSize [1.5,1.5];
_markerRef setMarkerType "n_inf";
_markerRef setMarkerDir -1;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_AAF_7", [23208.1,18646.5,0]];
_markerRef setMarkerColor "ColorGUER";
_markerRef setMarkerSize [1,1];
_markerRef setMarkerType "n_plane";
_markerRef setMarkerDir 0;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_AAF_9", [16240.8,12496.7,0]];
_markerRef setMarkerColor "ColorGUER";
_markerRef setMarkerSize [0.75,0.75];
_markerRef setMarkerType "n_naval";
_markerRef setMarkerDir -1;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";

_markerRef = createMarker ["BIS_ORBAT_NATO_1", [12276.7,12321.7,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [1,1];
_markerRef setMarkerType "b_inf";
_markerRef setMarkerDir -0.3;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_NATO_2", [15335.7,17357.6,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [1,1];
_markerRef setMarkerType "b_inf";
_markerRef setMarkerDir 0;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_NATO_3", [16964.4,12101.4,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [1,1];
_markerRef setMarkerType "b_inf";
_markerRef setMarkerDir 1;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";

_markerRef = createMarker ["BIS_ORBAT_CSAT_1", [16074.4,16584.3,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [0.75,0.75];
_markerRef setMarkerType "o_inf";
_markerRef setMarkerDir 0.5;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_CSAT_2", [10987.1,11167.6,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [0.75,0.75];
_markerRef setMarkerType "o_inf";
_markerRef setMarkerDir 0;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";

_markerRef = createMarker ["BIS_ORBAT_size_1", [11249.4,12531.4,0]];
_markerRef setMarkerColor "Default";
_markerRef setMarkerSize [1.5,1.5];
_markerRef setMarkerType "group_5";
_markerRef setMarkerDir -1;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_size_2", [12280.9,12385.7,0]];
_markerRef setMarkerColor "Default";
_markerRef setMarkerSize [1,1];
_markerRef setMarkerType "group_2";
_markerRef setMarkerDir -0.3;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_size_3", [11963.3,11389.8,0]];
_markerRef setMarkerColor "Default";
_markerRef setMarkerSize [1.5,1.5];
_markerRef setMarkerType "group_5";
_markerRef setMarkerDir 1;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_size_4", [10991.9,11201,0]];

_markerRef setMarkerColor "Default";
_markerRef setMarkerSize [1,1];
_markerRef setMarkerType "group_1";
_markerRef setMarkerDir 0;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_size_5", [14244.6,17056.7,0]];
_markerRef setMarkerColor "Default";
_markerRef setMarkerSize [1.5,1.5];
_markerRef setMarkerType "group_4";
_markerRef setMarkerDir -1;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_size_6", [15336.9,17409.9,0]];
_markerRef setMarkerColor "Default";
_markerRef setMarkerSize [1,1];
_markerRef setMarkerType "group_2";
_markerRef setMarkerDir 0;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_size_7", [16078.6,16605.3,0]];
_markerRef setMarkerColor "Default";
_markerRef setMarkerSize [1,1];
_markerRef setMarkerType "group_1";
_markerRef setMarkerDir 0.5;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_size_8", [14162.3,15499.7,0]];
_markerRef setMarkerColor "Default";
_markerRef setMarkerSize [1.5,1.5];
_markerRef setMarkerType "group_6";
_markerRef setMarkerDir 2;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_size_9", [15237.9,16033.9,0]];
_markerRef setMarkerColor "Default";
_markerRef setMarkerSize [1.5,1.5];
_markerRef setMarkerType "group_7";
_markerRef setMarkerDir 1;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_size_10", [23190.7,18740.7,0]];
_markerRef setMarkerColor "Default";
_markerRef setMarkerSize [1,1];
_markerRef setMarkerType "group_3";
_markerRef setMarkerDir 0;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_size_11", [16963.3,12114.5,0]];
_markerRef setMarkerColor "Default";
_markerRef setMarkerSize [1,1];
_markerRef setMarkerType "group_2";
_markerRef setMarkerDir 2;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_ORBAT_size_12", [15281.7,11595.8,0]];
_markerRef setMarkerColor "Default";
_markerRef setMarkerSize [1,1];
_markerRef setMarkerType "group_3";
_markerRef setMarkerDir 2;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
