_markerRef = createMarker ["BIS_mrk_frontline_FIA_1", [14575,21915.8,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [1000,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 125.422;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_2", [13388,20858.3,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [750,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 155.549;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_3", [12438.8,19989.9,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [750,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 299.182;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_4", [11799.9,18651.4,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [800,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 472.062;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_5", [10916.5,16937,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [1200,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 478.979;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_6", [9927.08,15504.2,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [600,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 495.593;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_7", [8979.01,14933.6,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [600,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 520.508;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_8", [7802.52,14814,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [700,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 545.112;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_9", [6362.64,15240.8,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [900,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 746.256;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_10", [5134.72,15951.9,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [600,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 573.94;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_11", [4479.4,16745,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [600,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 605.612;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_12", [3676.97,18428.5,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [1300,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 423.948;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_13", [3007.13,19618,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [200,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 572.908;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_14", [2718.86,19743.6,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [200,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 557.754;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_1", [14630.1,19729.6,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [1000,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -37.409;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_2", [13178.8,17883.1,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [1500,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -59.8718;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_3", [11687.7,16015.1,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [1000,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -38.2315;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_4", [10306.1,14750.9,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [1000,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -44.3006;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_5", [9087.97,13961.6,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [700,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -195.877;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_6", [7815.94,13695.7,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [700,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -367.663;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_7", [6235.81,13692.6,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [1000,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 6.8208;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_8", [16257.5,20629.8,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [1000,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -197.928;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_10", [4191.27,13929.9,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [1200,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 6.06189;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_12", [14834.6,16413.2,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [1500,1000];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -223.701;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_14", [14946.2,14206.4,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [1,1];
_markerRef setMarkerType "mil_arrow";
_markerRef setMarkerDir 2.12877;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
