_markerRef = createMarker ["BIS_mrk_frontline_FIA_2", [12995.9,22891.6,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [300,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 111.802;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_3", [12440.9,22124.4,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [750,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 312.098;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_4", [11548.7,21020,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [750,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 304.753;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_5", [10610.7,19353.5,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [1200,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 476.058;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_6", [9675.95,17993.1,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [600,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 504.254;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_7", [8696.19,17484.5,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [600,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 520.508;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_8", [7667.2,17367.5,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [600,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 545.112;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_9", [6334.7,17653.8,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [900,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 736.372;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_10", [5060.68,18208.1,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [600,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 573.94;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_11", [4405.36,19001.3,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [600,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 605.612;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_12", [3728.18,20420.8,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [1000,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 423.948;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_FIA_14", [3080.75,21422.6,0]];
_markerRef setMarkerColor "ColorWEST";
_markerRef setMarkerSize [400,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 582.839;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_1", [14621.2,19662.5,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [1000,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -37.409;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_2", [13143,17847.4,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [1500,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -59.8718;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_3", [11687.7,16015.1,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [1000,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -38.2315;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_4", [10306.1,14750.9,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [1000,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -44.3006;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_5", [9087.97,13961.6,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [700,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -195.877;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_6", [7815.94,13695.7,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [700,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -367.663;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_7", [6235.81,13692.6,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [1000,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 6.8208;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_8", [16257.5,20509,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [1000,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -197.928;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_10", [4191.27,13929.9,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [1200,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 6.06189;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontline_CSAT_13", [14834.6,16413.2,0]];
_markerRef setMarkerColor "ColorEAST";
_markerRef setMarkerSize [1500,1000];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -223.701;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
