_markerRef = createMarker ["BIS_mrk_frontlines_NATO_1", [1918.19,2952.28,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [80,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -5.00809;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontlines_NATO_3", [2319.13,3086.52,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [350,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -21.983;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontlines_NATO_4", [2894.87,3428.18,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [350,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 141.586;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontlines_NATO_5", [3466.26,3644.2,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [350,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 176.646;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontlines_NATO_6", [4183.58,3465.53,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [450,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 386.886;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontlines_NATO_7", [4733.29,3051.97,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [300,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 411.793;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
