_markerRef = createMarker ["BIS_mrk_frontlines_NATO_3", [2149.09,3800.94,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [350,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -8.3625;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontlines_NATO_4", [2838.22,3884.43,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [350,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -5.81612;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontlines_NATO_5", [3510.67,4018.28,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [350,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 164.163;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontlines_NATO_6", [4280.58,4148.07,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [450,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 354.578;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontlines_NATO_7", [5013.68,4147.77,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [300,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 188.719;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontlines_NATO_8", [5543.63,4013.98,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [270,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 379.115;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
