_markerRef = createMarker ["BIS_mrk_frontlines_NATO_2", [1911.69,3060.34,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [60,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 172.424;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontlines_NATO_3", [2310.57,3147.11,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [350,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 167.176;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontlines_NATO_4", [2894.87,3428.18,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [350,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 141.586;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontlines_NATO_5", [3457.62,3759.42,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [350,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 157.163;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontlines_NATO_6", [3979.11,4084.83,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [300,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 318.409;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontlines_NATO_7", [4512.25,4264.58,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [340,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 1.18796;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrk_frontlines_NATO_8", [5300.6,4086.05,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [500,60];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 20.6677;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Vertical";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
