_markerRef = createMarker ["BIS_mrkHUB_4", [3128.03,21977.6,0]];
_markerRef setMarkerColor "ColorYellow";
_markerRef setMarkerSize [5,7];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -31.7759;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_mrkHUB_5", [3128.76,21989.4,0]];
_markerRef setMarkerColor "ColorGreen";
_markerRef setMarkerSize [4,6];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -24.5691;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_mrkHUB_8", [3170.11,21910.8,0]];
_markerRef setMarkerColor "ColorGreen";
_markerRef setMarkerSize [4,6];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -86.8798;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";

_markerRef = createMarker ["BIS_mrkHUB_1", [3128.32,21990,0]];
_markerRef setMarkerColor "ColorGreen";
_markerRef setMarkerSize [1.5,1.5];
_markerRef setMarkerType "hd_destroy";
_markerRef setMarkerDir 359.974;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "DiagGrid";
_markerRef setMarkerText "Armory";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_mrkHUB_2", [3128.51,21977.6,0]];
_markerRef setMarkerColor "ColorYellow";
_markerRef setMarkerSize [2,2];
_markerRef setMarkerType "hd_destroy";
_markerRef setMarkerDir 268.511;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "DiagGrid";
_markerRef setMarkerText "Briefing Area";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_mrkHUB_6", [3169.56,21911.2,0]];
_markerRef setMarkerColor "ColorGreen";
_markerRef setMarkerSize [1,1];
_markerRef setMarkerType "hd_destroy";
_markerRef setMarkerDir 268.61;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "DiagGrid";
_markerRef setMarkerText "Exfill Point";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_mrkHUB_10", [3151.48,21959,0]];
_markerRef setMarkerColor "Default";
_markerRef setMarkerSize [80,80];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 0;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Border";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";

#include "markers_for_hubs_shared.hpp"