//coarse  markers
_markerRef = createMarker ["BIS_airBase", [1947.86,5487.75,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [350,800];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 14.9414;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mike26", [4401.88,3789.27,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [200,200];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 0;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_maxwell", [3297.11,2941.1,0]];
_markerRef setMarkerColor "ColorBLUFOR";
_markerRef setMarkerSize [300,300];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 0;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_tempest", [1980.08,3523.04,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [100,100];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 0;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_village", [2026.12,2722.06,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [150,100];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 0;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_rogain", [5043.62,5897.67,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [100,100];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 0;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_Kamino", [6526.48,5345.72,0]];
_markerRef setMarkerColor "ColorIndependent";
_markerRef setMarkerSize [300,100];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 23.0945;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "FDiagonal";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_mrkUnknown01", [2373.99,5482.28,0]];
_markerRef setMarkerColor "Default";
_markerRef setMarkerSize [2,2];
_markerRef setMarkerType "mil_unknown";
_markerRef setMarkerDir 0;
_markerRef setMarkerAlpha 0.25;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_mrkUnknown02", [5202.86,6059.48,0]];
_markerRef setMarkerColor "Default";
_markerRef setMarkerSize [1.5,1.5];
_markerRef setMarkerType "mil_unknown";
_markerRef setMarkerDir 0;
_markerRef setMarkerAlpha 0.25;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_mrkUnknown03", [6468.88,5259.92,0]];
_markerRef setMarkerColor "Default";
_markerRef setMarkerSize [1.6,1.6];
_markerRef setMarkerType "mil_unknown";
_markerRef setMarkerDir 0;
_markerRef setMarkerAlpha 0.25;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ICON";

//HUB detailed markers
_markerRef = createMarker ["BIS_mrkHUB_8", [3298.21,2888.91,0]];
_markerRef setMarkerColor "ColorGreen";
_markerRef setMarkerSize [4,6];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -86.8798;
_markerRef setMarkerAlpha 0.99;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_mrkHUB_4", [3277.79,2930.94,0]];
_markerRef setMarkerColor "ColorYellow";
_markerRef setMarkerSize [8,9];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -31.7759;
_markerRef setMarkerAlpha 0.99;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_mrkHUB_5", [3263.82,2915.89,0]];
_markerRef setMarkerColor "ColorGreen";
_markerRef setMarkerSize [4,6];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -24.5691;
_markerRef setMarkerAlpha 0.99;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";

_markerRef = createMarker ["BIS_mrkHUB_1", [3263.39,2916.51,0]];
_markerRef setMarkerColor "ColorGreen";
_markerRef setMarkerSize [1.5,1.5];
_markerRef setMarkerType "mil_destroy";
_markerRef setMarkerDir 359.974;
_markerRef setMarkerAlpha 0.99;
_markerRef setMarkerBrush "DiagGrid";
_markerRef setMarkerText "@str_a3_a_hub_marker_hub_armory";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_mrkHUB_2", [3277.42,2930.85,0]];
_markerRef setMarkerColor "ColorYellow";
_markerRef setMarkerSize [2,2];
_markerRef setMarkerType "mil_destroy";
_markerRef setMarkerDir 268.511;
_markerRef setMarkerAlpha 0.99;
_markerRef setMarkerBrush "DiagGrid";
_markerRef setMarkerText "@str_a3_a_hub_marker_hub_briefing_area";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_mrkHUB_6", [3297.67,2889.36,0]];
_markerRef setMarkerColor "ColorGreen";
_markerRef setMarkerSize [1,1];
_markerRef setMarkerType "mil_destroy";
_markerRef setMarkerDir 268.61;
_markerRef setMarkerAlpha 0.99;
_markerRef setMarkerBrush "DiagGrid";
_markerRef setMarkerText "@str_a3_a_hub_marker_hub_assemble_point";
_markerRef setMarkerShape "ICON";

//this marker sets the zone where detailed markers are shown
_markerRef = createMarker ["BIS_mrkHUB_10", [3295.22,2937.78,0]];
_markerRef setMarkerColor "ColorBLUFOR";
_markerRef setMarkerSize [80,80];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 0;
_markerRef setMarkerAlpha 0.0100004;
_markerRef setMarkerBrush "Border";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";

 #include "markers_for_hubs_shared.hpp"