_markerRef = createMarker ["BIS_mrkHUB_8", [8301.74,14816.4,0]];
_markerRef setMarkerColor "ColorGreen";
_markerRef setMarkerSize [4,6];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -86.8798;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_mrkHUB_4", [8238.59,14885.8,0]];
_markerRef setMarkerColor "ColorYellow";
_markerRef setMarkerSize [8,9];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -31.7759;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_mrkHUB_5", [8261.53,14845.8,0]];
_markerRef setMarkerColor "ColorGreen";
_markerRef setMarkerSize [4,6];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -24.5691;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_mrkHUB_1", [8261.1,14846.4,0]];
_markerRef setMarkerColor "ColorGreen";
_markerRef setMarkerSize [1,1];
_markerRef setMarkerType "hd_destroy";
_markerRef setMarkerDir 359.974;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "DiagGrid";
_markerRef setMarkerText "Armory";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_mrkHUB_2", [8238.22,14885.8,0]];
_markerRef setMarkerColor "ColorYellow";
_markerRef setMarkerSize [1,1];
_markerRef setMarkerType "hd_destroy";
_markerRef setMarkerDir 268.511;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "DiagGrid";
_markerRef setMarkerText "Briefing Area";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_mrkHUB_6", [8301.2,14816.8,0]];
_markerRef setMarkerColor "ColorGreen";
_markerRef setMarkerSize [1,1];
_markerRef setMarkerType "hd_destroy";
_markerRef setMarkerDir 268.61;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "DiagGrid";
_markerRef setMarkerText "Exfill Point";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_mrkHUB_10", [8237.32,14853.1,0]];
_markerRef setMarkerColor "Default";
_markerRef setMarkerSize [80,80];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 0;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Border";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";

#include "markers_for_hubs_shared.hpp"