_markerRef = createMarker ["BIS_mrkHUB_12", [5412.1,17895.3,0]];
_markerRef setMarkerColor "ColorGreen";
_markerRef setMarkerSize [8,10];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -24.5691;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_mrkHUB_4", [5409.11,17934.6,0]];
_markerRef setMarkerColor "ColorYellow";
_markerRef setMarkerSize [8,9];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -31.7759;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_mrkHUB_5", [5364.02,17926.4,0]];
_markerRef setMarkerColor "ColorGreen";
_markerRef setMarkerSize [4,6];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -24.5691;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";
_markerRef = createMarker ["BIS_mrkHUB_8", [5450.71,17926.2,0]];
_markerRef setMarkerColor "ColorGreen";
_markerRef setMarkerSize [4,6];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir -86.8798;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Solid";
_markerRef setMarkerText "";
_markerRef setMarkerShape "ELLIPSE";

_markerRef = createMarker ["BIS_mrkHUB_1", [5363.59,17927,0]];
_markerRef setMarkerColor "ColorGreen";
_markerRef setMarkerSize [1.5,1.5];
_markerRef setMarkerType "hd_destroy";
_markerRef setMarkerDir 359.974;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "DiagGrid";
_markerRef setMarkerText "Armory";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_mrkHUB_2", [5408.73,17934.6,0]];
_markerRef setMarkerColor "ColorYellow";
_markerRef setMarkerSize [2,2];
_markerRef setMarkerType "hd_destroy";
_markerRef setMarkerDir 268.511;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "DiagGrid";
_markerRef setMarkerText "Briefing Area";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_mrkHUB_6", [5450.16,17926.6,0]];
_markerRef setMarkerColor "ColorGreen";
_markerRef setMarkerSize [1,1];
_markerRef setMarkerType "hd_destroy";
_markerRef setMarkerDir 268.61;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "DiagGrid";
_markerRef setMarkerText "Exfill Point";
_markerRef setMarkerShape "ICON";
_markerRef = createMarker ["BIS_mrkHUB_10", [5401.91,17908.1,0]];
_markerRef setMarkerColor "Default";
_markerRef setMarkerSize [80,80];
_markerRef setMarkerType "Empty";
_markerRef setMarkerDir 0;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "Border";
_markerRef setMarkerText "";
_markerRef setMarkerShape "RECTANGLE";
_markerRef = createMarker ["BIS_mrkHUB_11", [5412.24,17896.3,0]];
_markerRef setMarkerColor "ColorGreen";
_markerRef setMarkerSize [1.5,1.5];
_markerRef setMarkerType "hd_destroy";
_markerRef setMarkerDir 359.974;
_markerRef setMarkerAlpha 1;
_markerRef setMarkerBrush "DiagGrid";
_markerRef setMarkerText "Shooting Range";
_markerRef setMarkerShape "ICON";

#include "markers_for_hubs_shared.hpp"