BIS_ORBAT_FIA_1 = createAgent  [ 'ModuleStrategicMapORBAT_F', [5764.65,21121.2,0], [], 0, 'NONE' ];
BIS_ORBAT_FIA_1 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_3"' ];
BIS_ORBAT_FIA_1 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_FIA"' ];
BIS_ORBAT_FIA_1 setVariable [ 'Tiers', '' ];
BIS_ORBAT_FIA_2 = createAgent  [ 'ModuleStrategicMapORBAT_F', [10001.1,18703.6,0], [], 0, 'NONE' ];
BIS_ORBAT_FIA_2 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_4"' ];
BIS_ORBAT_FIA_2 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_FIA"' ];
BIS_ORBAT_FIA_2 setVariable [ 'Tiers', '' ];
BIS_ORBAT_FIA_3 = createAgent  [ 'ModuleStrategicMapORBAT_F', [10656.4,8056.83,0], [], 0, 'NONE' ];
BIS_ORBAT_FIA_3 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_2"' ];
BIS_ORBAT_FIA_3 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_FIA"' ];
BIS_ORBAT_FIA_3 setVariable [ 'Tiers', '' ];
BIS_ORBAT_FIA_4 = createAgent  [ 'ModuleStrategicMapORBAT_F', [5662.77,17931.5,0], [], 0, 'NONE' ];
BIS_ORBAT_FIA_4 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_1"' ];
BIS_ORBAT_FIA_4 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_FIA"' ];
BIS_ORBAT_FIA_4 setVariable [ 'Tiers', '' ];
BIS_ORBAT_AAF_1 = createAgent  [ 'ModuleStrategicMapORBAT_F', [15289.6,17692.4,0], [], 0, 'NONE' ];
BIS_ORBAT_AAF_1 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "I_BCompany"' ];
BIS_ORBAT_AAF_1 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "I_AAF"' ];
BIS_ORBAT_AAF_1 setVariable [ 'Tiers', '2' ];
BIS_ORBAT_AAF_7 = createAgent  [ 'ModuleStrategicMapORBAT_F', [11555.4,11904.3,0], [], 0, 'NONE' ];
BIS_ORBAT_AAF_7 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "I_HelicopterSquadron"' ];
BIS_ORBAT_AAF_7 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "I_AAF"' ];
BIS_ORBAT_AAF_7 setVariable [ 'Tiers', '2' ];
BIS_ORBAT_AAF_8 = createAgent  [ 'ModuleStrategicMapORBAT_F', [14265.4,15672.6,0], [], 0, 'NONE' ];
BIS_ORBAT_AAF_8 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "O_A"' ];
BIS_ORBAT_AAF_8 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "O_Brigade"' ];
BIS_ORBAT_AAF_8 setVariable [ 'Tiers', '2' ];
BIS_ORBAT_CSAT_1 = createAgent  [ 'ModuleStrategicMapORBAT_F', [16436.4,16748.4,0], [], 0, 'NONE' ];
BIS_ORBAT_CSAT_1 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "O_2"' ];
BIS_ORBAT_CSAT_1 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "O_Brigade"' ];
BIS_ORBAT_CSAT_1 setVariable [ 'Tiers', '2' ];
