BIS_ORBAT_FIA_1 = createAgent  [ 'ModuleStrategicMapORBAT_F', [7062.43,21910.4,0], [], 0, 'NONE' ];
BIS_ORBAT_FIA_1 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_3"' ];
BIS_ORBAT_FIA_1 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_FIA"' ];
BIS_ORBAT_FIA_1 setVariable [ 'Tiers', '' ];
BIS_ORBAT_FIA_2 = createAgent  [ 'ModuleStrategicMapORBAT_F', [9732.3,18776.2,0], [], 0, 'NONE' ];
BIS_ORBAT_FIA_2 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_4"' ];
BIS_ORBAT_FIA_2 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_FIA"' ];
BIS_ORBAT_FIA_2 setVariable [ 'Tiers', '' ];
BIS_ORBAT_FIA_3 = createAgent  [ 'ModuleStrategicMapORBAT_F', [10387.6,8129.4,0], [], 0, 'NONE' ];
BIS_ORBAT_FIA_3 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_2"' ];
BIS_ORBAT_FIA_3 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_FIA"' ];
BIS_ORBAT_FIA_3 setVariable [ 'Tiers', '' ];
BIS_ORBAT_FIA_4 = createAgent  [ 'ModuleStrategicMapORBAT_F', [5393.93,18004.1,0], [], 0, 'NONE' ];
BIS_ORBAT_FIA_4 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_1"' ];
BIS_ORBAT_FIA_4 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_FIA"' ];
BIS_ORBAT_FIA_4 setVariable [ 'Tiers', '' ];
BIS_ORBAT_AAF_1 = createAgent  [ 'ModuleStrategicMapORBAT_F', [15020.8,17764.9,0], [], 0, 'NONE' ];
BIS_ORBAT_AAF_1 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "I_BCompany"' ];
BIS_ORBAT_AAF_1 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "I_AAF"' ];
BIS_ORBAT_AAF_1 setVariable [ 'Tiers', '2' ];
BIS_ORBAT_AAF_7 = createAgent  [ 'ModuleStrategicMapORBAT_F', [11286.6,11976.9,0], [], 0, 'NONE' ];
BIS_ORBAT_AAF_7 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "I_HelicopterSquadron"' ];
BIS_ORBAT_AAF_7 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "I_AAF"' ];
BIS_ORBAT_AAF_7 setVariable [ 'Tiers', '2' ];
BIS_ORBAT_AAF_8 = createAgent  [ 'ModuleStrategicMapORBAT_F', [13996.6,15745.2,0], [], 0, 'NONE' ];
BIS_ORBAT_AAF_8 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "O_A"' ];
BIS_ORBAT_AAF_8 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "O_Brigade"' ];
BIS_ORBAT_AAF_8 setVariable [ 'Tiers', '2' ];
BIS_ORBAT_AAF_9 = createAgent  [ 'ModuleStrategicMapORBAT_F', [15320,11172.2,0], [], 0, 'NONE' ];
BIS_ORBAT_AAF_9 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "I_D_1"' ];
BIS_ORBAT_AAF_9 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "I_1stRegiment"' ];
BIS_ORBAT_AAF_9 setVariable [ 'Tiers', '2' ];
BIS_ORBAT_AAF_10 = createAgent  [ 'ModuleStrategicMapORBAT_F', [21400.3,7059.76,0], [], 0, 'NONE' ];
BIS_ORBAT_AAF_10 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "I_D_4"' ];
BIS_ORBAT_AAF_10 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "I_1stRegiment"' ];
BIS_ORBAT_AAF_10 setVariable [ 'Tiers', '2' ];
BIS_ORBAT_CSAT_1 = createAgent  [ 'ModuleStrategicMapORBAT_F', [16497.4,16843.4,0], [], 0, 'NONE' ];
BIS_ORBAT_CSAT_1 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "O_2"' ];
BIS_ORBAT_CSAT_1 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "O_Brigade"' ];
BIS_ORBAT_CSAT_1 setVariable [ 'Tiers', '2' ];
