BIS_ORBAT_FIA_1 = createAgent  [ 'ModuleStrategicMapORBAT_F', [4127.96,19074.4,0], [], 0, 'NONE' ];
BIS_ORBAT_FIA_1 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_3"' ];
BIS_ORBAT_FIA_1 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_FIA"' ];
BIS_ORBAT_FIA_1 setVariable [ 'Tiers', '' ];
BIS_ORBAT_FIA_2 = createAgent  [ 'ModuleStrategicMapORBAT_F', [9130.29,17005.6,0], [], 0, 'NONE' ];
BIS_ORBAT_FIA_2 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_4"' ];
BIS_ORBAT_FIA_2 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_FIA"' ];
BIS_ORBAT_FIA_2 setVariable [ 'Tiers', '' ];
BIS_ORBAT_FIA_3 = createAgent  [ 'ModuleStrategicMapORBAT_F', [12498.2,7044.41,0], [], 0, 'NONE' ];
BIS_ORBAT_FIA_3 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_2"' ];
BIS_ORBAT_FIA_3 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_FIA"' ];
BIS_ORBAT_FIA_3 setVariable [ 'Tiers', '' ];
BIS_ORBAT_FIA_4 = createAgent  [ 'ModuleStrategicMapORBAT_F', [3143,21996.6,0], [], 0, 'NONE' ];
BIS_ORBAT_FIA_4 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_1"' ];
BIS_ORBAT_FIA_4 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "B_I_FIA"' ];
BIS_ORBAT_FIA_4 setVariable [ 'Tiers', '' ];
BIS_ORBAT_AAF_1 = createAgent  [ 'ModuleStrategicMapORBAT_F', [15135,17746.4,0], [], 0, 'NONE' ];
BIS_ORBAT_AAF_1 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "I_BCompany"' ];
BIS_ORBAT_AAF_1 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "I_AAF"' ];
BIS_ORBAT_AAF_1 setVariable [ 'Tiers', '2' ];
BIS_ORBAT_AAF_7 = createAgent  [ 'ModuleStrategicMapORBAT_F', [11400.8,11958.3,0], [], 0, 'NONE' ];
BIS_ORBAT_AAF_7 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "I_HelicopterSquadron"' ];
BIS_ORBAT_AAF_7 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "I_AAF"' ];
BIS_ORBAT_AAF_7 setVariable [ 'Tiers', '2' ];
BIS_ORBAT_AAF_8 = createAgent  [ 'ModuleStrategicMapORBAT_F', [14110.8,15726.6,0], [], 0, 'NONE' ];
BIS_ORBAT_AAF_8 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "O_A"' ];
BIS_ORBAT_AAF_8 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "O_Brigade"' ];
BIS_ORBAT_AAF_8 setVariable [ 'Tiers', '2' ];
BIS_ORBAT_CSAT_1 = createAgent  [ 'ModuleStrategicMapORBAT_F', [16611.6,16824.8,0], [], 0, 'NONE' ];
BIS_ORBAT_CSAT_1 setVariable [ 'Path', 'configfile >> "CfgORBAT" >> "BIS" >> "O_2"' ];
BIS_ORBAT_CSAT_1 setVariable [ 'Parent', 'configfile >> "CfgORBAT" >> "BIS" >> "O_Brigade"' ];
BIS_ORBAT_CSAT_1 setVariable [ 'Tiers', '2' ];
